version: '2'
services:
 
 compile:
  image: gradle/example
  build:
   context: .
  command: ./gradlew build
  environment:
   - /.android
  volumes:
   - gradle-cache:/home/gradle/.gradle
   - gradle-cache:/home/gradle/build
   - ./project:/opt/workspace

 run:
  image: gradle/example
  build:
   context: .
  command: ./gradlew installDebug
  volumes:
   - gradle-cache:/home/gradle/.gradle
   - gradle-cache:/home/gradle/build

volumes:
 gradle-cache:
