version: '2'
services:
 
 compile:
  image: chibatching/docker-android-sdk
  command: ./gradlew build
  privileged: true
  environment:
   - /.android
  volumes:
   - gradle-cache:/home/gradle/.gradle
   - gradle-cache:/home/gradle/build
   - ./project:/opt/workspace
   - /dev/bus/usb:/dev/bus/usb 

 run:
  image: marcelmaatkamp/android-gradle
  build:
   context: .
  command: ./gradlew installDebug
  volumes:
   - gradle-cache:/home/gradle/.gradle
   - gradle-cache:/home/gradle/build

volumes:
 gradle-cache:
